data_2019 <- read.csv("ahs2019n.csv")
data_2017 <- read.csv("ahs2017n.csv")
data_2015 <- read.csv("ahs2015n.csv")

data_2019$YEAR <- 2019
data_2017$YEAR <- 2017
data_2015$YEAR <- 2015


library(dplyr)


#subset dataframe
data_2019 <- data_2019 %>% 
  select(CONTROL, OMB13CBSA, TENURE, MARKETVAL, HINCP, HHAGE, HHSPAN, HHRACE, PERPOVLVL, HHGRAD, TOTHCAMT, YRBUILT,
         RENT, MORTAMT, PROTAXAMT, INSURAMT, FIRSTHOME, RENTCNTRL, LOANTYPE1, YEAR, BEDROOMS, BATHROOMS,
         UNITSIZE, RATINGHS, RATINGNH)

data_2017 <- data_2017 %>% 
  select(CONTROL, OMB13CBSA, TENURE, MARKETVAL, HINCP, HHAGE, HHSPAN, HHRACE, PERPOVLVL, HHGRAD, TOTHCAMT, YRBUILT,
         RENT, MORTAMT, PROTAXAMT, INSURAMT, FIRSTHOME, RENTCNTRL, LOANTYPE1, YEAR, BEDROOMS, BATHROOMS,
         UNITSIZE, RATINGHS, RATINGNH)

data_2015 <- data_2015 %>% 
  select(CONTROL, OMB13CBSA, TENURE, MARKETVAL, HINCP, HHAGE, HHSPAN, HHRACE, PERPOVLVL, HHGRAD, TOTHCAMT, YRBUILT,
         RENT, MORTAMT, PROTAXAMT, INSURAMT, FIRSTHOME, RENTCNTRL, LOANTYPE1, YEAR, BEDROOMS, BATHROOMS,
         UNITSIZE, RATINGHS, RATINGNH)

merge <- rbind(data_2019, data_2017)
d <- rbind(merge, data_2015)
